f = open(input('Введите название и путь файла: '))
d = f.read()
a = d.count(input('Введите символ: '))
b = d.replace(input('Введите  символ который хотите поменять: '), input('Введите символ замены: '))
print(a)
print(b)
